ALTER TABLE LINIA_COMANDA DROP FOREIGN KEY FK_lincomanda_prod;
ALTER TABLE LINIA_COMANDA DROP FOREIGN KEY FK_lincomanda_com;
ALTER TABLE COMANDA DROP FOREIGN KEY FK_comanda_client;
ALTER TABLE COMANDA DROP FOREIGN KEY FK_comanda_empl;
ALTER TABLE OFICINES DROP FOREIGN KEY FK_ofic_empl;
ALTER TABLE EMPLEATS DROP FOREIGN KEY FK_empl_ofic;
ALTER TABLE EMPLEATS DROP FOREIGN KEY FK_empl_empl;

